### ISSUE TITLE
Better design

### ISSUE THREAD

**Issue by woook** [eastgenomics/eggd_vcf_handler_for_uranus#15]
- Consider refactoring how VEP is called
- Consider parallelising VEP/docker, e.g. https://stackoverflow.com/questions/56040426/parallel-code-execution-in-docker-containers
- Alternatively, annotate once and transcript/panel filter many times

**Comment by jethror1** [comment]
- caling of VEP refactored in 2.2.0 update
- annotating once then filtering by transcript lists does not seem possible at the moment: https://github.com/Ensembl/ensembl-vep/issues/1063
- hopefully will be fixed in vep to allow this

**Comment by jethror1** [comment]
Putting these here so I remember them:
- https://www.ensembl.org/info/docs/tools/vep/script/vep_options.html#opt_symbol
- https://m.ensembl.org/info/docs/tools/vep/script/vep_filter.html
