### ISSUE TITLE
Utilise more cores

### ISSUE THREAD

**Issue by mattgarner** [eastgenomics/eggd_vcf_handler_for_uranus#18]
Could we consider adding `--fork` to the VEP commands to speed things up? It only looks to be using 1/4 cores currently.

More details: https://m.ensembl.org/info/docs/tools/vep/script/vep_other.html#faster

**Comment by jethror1** [comment]
Adding `--fork 4` doesn't seemed to have made any difference to run time, same for instance with 8 cores and using `--fork 8`:

original job: https://platform.dnanexus.com/projects/G59YjF04Y2yzJFv894qZYPPZ/monitor/job/G59Yv3Q4Y2yg4J6b4ZXj2gkx

test job: https://platform.dnanexus.com/projects/G5BggKQ4VQ3zq3yqPFFZz501/monitor/job/G5BpQq84VQ3fJb6YKfX4gj8p

test job (with 8 cores): https://platform.dnanexus.com/projects/G5BggKQ4VQ3zq3yqPFFZz501/monitor/job/G5Bkp2j4VQ3fkK2X81XQ299V

**Comment by jethror1** [comment]
veps default buffer size to split vcfs by using `--fork` is 5000, for myeloid a vcf after bein restricted by the panel is ~500, which would explain why it didn't affect run time.

Running vep annotation for myeloid samples takes ~ 4 minutes each time, and the docs suggesting lowering the buffer size less than default is unlikely to improve run time, so can this be closed?
