### ISSUE TITLE
What about homozygous variants?

### ISSUE THREAD

**Issue by woook** [eastgenomics/eggd_vcf_handler_for_uranus#3]
https://github.com/eastgenomics/eggd_vcf_handler_for_uranus/blob/b01a051766e6cc51e25a10fd958da5f4d1148e8d/resources/home/dnanexus/mutect2_vcf_2_BSVI_v1.2.0.py#L72

What is the effect of the current genotype re-writing on homozygous variants?
Are we in danger of calling something het when it's hom?

**Comment by mattgarner** [comment]
Context:
```
if len(sample[0]) > 3:
            # >3 => not 0/1 => modify
            sample[0] = '0/1'
```

Homozygous variants will have a genotype like `1` or `1/1`
in which case `len(sample[0]) > 3` == `False` so we don't enter this block

`1/2` genotypes similarly will not be modified by this block.

I checked what GTs we get in a vcf:
```
zcat 2100595_21025Z0004_BM_AML_MYE_M__EGG_S9_L006_markdup_recalibrated_tnhaplotyper2.vcf.gz | grep -v ^# | cut -f 10 | awk -F ":" '{print $1}' | sort | uniq -c
  35850 0/1
    192 0/1/2
     72 0/1/2/3
     22 0/1/2/3/4
     17 0/1/2/3/4/5
     11 0/1/2/3/4/5/6
      3 0/1/2/3/4/5/6/7
      1 0/1/2/3/4/5/6/7/8
      1 0/1/2/3/4/5/6/7/8/9/10/11/12
```
No homs found

**Comment by woook** [comment]
Thanks Matt. I also checked the VCF and found no 1/1's.
Is 1/1/2/3 a possibility?

**Comment by jethror1** [comment]
can also add a check to only replace 0/*, then we would never modify homs?

**Comment by woook** [comment]
Might be worthwhile just in case although I don't mind if this is left for next time considering it appears to be a corner case.

**Comment by woook** [comment]
As we are moving away from BSVI (& therefore the "BSVI VCF") and this fudging of GT has been removed from the text output (in #11), going to close this issue.
