### ISSUE TITLE
Intermediate VCF output

### ISSUE THREAD

**Issue by Aisha-D** [eastgenomics/eggd_vcf_handler_for_uranus#43]
Output VCF after region of interest and variant quality filtering are applied. Currently, all outputs have been run through VEP or the python script.

Also do we still need to produce panel based VCFs?? These outputs are never used.

**Comment by jethror1** [comment]
as in output unannotated vcf?

And probably not to the panel vcfs, we did that so that the excel isn't the only place those variants exist to sense check what is in the vcfs is in each tab
